name: visp-gpu-ws
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - cmake
  - cxx-compiler
  - eigen
  - libdc1394
  - libgomp
  - libjpeg-turbo
  - libopencv
  - libpng
  - librealsense
  - libxml2
  - make
  - mkl-devel
  - nlohmann_json
  - pkg-config
  - pybind11
  - xorg-libx11
  - xorg-libxfixes
  - xorg-xorgproto
  - fmt
  - pinocchio
  - poco
  - conda-forge::opencv
  - anaconda::yaml
  - anaconda::pyyaml
  - matplotlib=3.10.3
  - anaconda::pandas
  - conda-forge::scienceplots
  - ca-certificates==2026.1.4
  - expat=2.7.0
  - level-zero=1.22.4
  - libabseil=20250127.1
  - libass=0.17.3
  - libexpat=2.7.0
  - libopenvino-auto-batch-plugin=2025.0.0
  - libopenvino-auto-plugin=2025.0.0
  - libopenvino-hetero-plugin=2025.0.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-ir-frontend=2025.0.0
  - libopenvino-onnx-frontend=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - libopenvino-pytorch-frontend=2025.0.0
  - libopenvino-tensorflow-frontend=2025.0.0
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - libopenvino=2025.0.0
  - libprotobuf=5.29.3
  - libwebp-base=1.5.0
  - libwebp=1.5.0
  - matplotlib-base=3.10.3
  - openssl==3.6.0
  - snappy=1.2.1
  - networkx=2.8.4
  - scikit-learn
  - conda-forge::pydantic
  - conda-forge::tabulate
  - pytorch-cuda==12.1
  - torchaudio
  - torchvision
  - nvidia::cuda-toolkit
  - conda-forge::texlive-core
  - anaconda::filelock
  - conda-forge::pydocstyle
  - conda-forge::h5py
